### ISSUE TITLE
accuracy between regular conv and asynet

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#14]
why is the accuracy of asynet lower than standard conv now that **Regular convolutions on the other hand generate blurry activation maps**?

**Comment by MessikommerNico** [comment]
There might be different reasons. In general, regular convolutions are less constrained than Sparse Convolutions (SSC). Additionally, as the active map for SSC is decided based on the input, the receptive field is changing with different inputs. This is not the case for regular convolutions due to the blurry activation maps, which "grow" constantly through the network layers
