### ISSUE TITLE
what is the main diference between SSC(Submanifold sparse convolutional networks) and SRR(Sparse Recursive Representations)?

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#4]
after reading the paper, i think SRR is an extension  of SSC in event data, can anyone explain that?

**Comment by 978326187** [comment]
i think the difference is that asynet propagate event-by-event.

**Comment by MessikommerNico** [comment]
That is correct. The difference between SSC and asynet is the possibility to propagate single events through the network. Due to the rule book formulation and the network state propagation through time, asynet reduces the number of FLOPS required to process single events or small batches of events. In comparison, SCC compute the activations of active sites even if the input did not change. This is not the case for asynet due to the network state propagation through time.
